// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBHRdv6F7PxvdzrG5v1Xi6MscAYfy-C8',
    appId: '1:305164950366:web:b2c06c3e3ba004817b0dcf',
    messagingSenderId: '305164950366',
    projectId: 'marinescope-aeb64',
    authDomain: 'marinescope-aeb64.firebaseapp.com',
    storageBucket: 'marinescope-aeb64.firebasestorage.app',
    measurementId: 'G-GMD53QCDK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_ZTbUNbB6oixqrLH8zwcFsDVvrFLK9E',
    appId: '1:305164950366:android:d89e62f97f19963c7b0dcf',
    messagingSenderId: '305164950366',
    projectId: 'marinescope-aeb64',
    storageBucket: 'marinescope-aeb64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxYL-6QPRUKujBWCP5PSzpbh-giU0UhmE',
    appId: '1:305164950366:ios:d1fa07bf0ec65c487b0dcf',
    messagingSenderId: '305164950366',
    projectId: 'marinescope-aeb64',
    storageBucket: 'marinescope-aeb64.firebasestorage.app',
    iosBundleId: 'com.marinescope.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxYL-6QPRUKujBWCP5PSzpbh-giU0UhmE',
    appId: '1:305164950366:ios:684fbc86236867dd7b0dcf',
    messagingSenderId: '305164950366',
    projectId: 'marinescope-aeb64',
    storageBucket: 'marinescope-aeb64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXBHRdv6F7PxvdzrG5v1Xi6MscAYfy-C8',
    appId: '1:305164950366:web:ef8edddf01cd58e27b0dcf',
    messagingSenderId: '305164950366',
    projectId: 'marinescope-aeb64',
    authDomain: 'marinescope-aeb64.firebaseapp.com',
    storageBucket: 'marinescope-aeb64.firebasestorage.app',
    measurementId: 'G-ZJ1HDK3WY1',
  );
}
